// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AccountName   string
	Balance       float32
	AccountNumber string
	SortCode      string
	UserID        int32
}

type OthersAccount struct {
	ID            int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AccountName   string
	AccountNumber string
	SortCode      string
	AccountID     uuid.UUID
}

type RevokedToken struct {
	Token     string
	RevokedAt time.Time
	UserID    int32
}

type Transaction struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TransactionTime time.Time
	Type            string
	Amount          float32
	PreBalance      float32
	PostBalance     float32
	NewAccount      bool
	Name            string
	AccountNumber   string
	SortCode        string
	AccountID       uuid.UUID
}

type User struct {
	ID             int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	HashedPassword string
}
