// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TransactionTime time.Time
	Type            string
	Amount          float32
	PreBalance      float32
	PostBalance     float32
	NewAccount      bool
	Name            string
	AccountNumber   string
	SortCode        string
	UserID          int32
}

type User struct {
	ID             int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	HashedPassword string
}
