// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id, 
    created_at, 
    updated_at, 
    transaction_time, 
    type, 
    amount, 
    pre_balance, 
    post_balance, 
    new_account, 
    name, 
    account_number, 
    sort_code, 
    user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, created_at, updated_at, transaction_time, type, amount, pre_balance, post_balance, new_account, name, account_number, sort_code, user_id
`

type CreateTransactionParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TransactionTime time.Time
	Type            string
	Amount          float32
	PreBalance      float32
	PostBalance     float32
	NewAccount      bool
	Name            string
	AccountNumber   string
	SortCode        string
	UserID          int32
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TransactionTime,
		arg.Type,
		arg.Amount,
		arg.PreBalance,
		arg.PostBalance,
		arg.NewAccount,
		arg.Name,
		arg.AccountNumber,
		arg.SortCode,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionTime,
		&i.Type,
		&i.Amount,
		&i.PreBalance,
		&i.PostBalance,
		&i.NewAccount,
		&i.Name,
		&i.AccountNumber,
		&i.SortCode,
		&i.UserID,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, created_at, updated_at, transaction_time, type, amount, pre_balance, post_balance, new_account, name, account_number, sort_code, user_id FROM transactions
`

func (q *Queries) GetTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionTime,
			&i.Type,
			&i.Amount,
			&i.PreBalance,
			&i.PostBalance,
			&i.NewAccount,
			&i.Name,
			&i.AccountNumber,
			&i.SortCode,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
